

FROM node:20-alpine

WORKDIR /appFrontend

# Install dependencies -> Copy package.json and package-lock.json into the container’s /app directory.
COPY package*.json ./

RUN npm install

# Copy all files fron local dir to working dir.
COPY . .

EXPOSE 5173

#Start dev server
CMD ["npm", "run", "dev", "--", "--host"]

